### ISSUE TITLE
Outpost Music Plays in Arena

### ISSUE THREAD

**Issue by Silentdarkness12** [wildweasel486/ww-drla-sounds#1]
When using this mod alongside DRLA+DRPG, the Outpost music can play while fighting in the arena. Normally, the music that plays in there is catchy techno/metal stuff. So yeah, that kinda breaks the mood...

**Comment by wildweasel486** [comment]
Will leave this alone until the new Outpost is finished.

**Comment by wildweasel486** [comment]
Have removed the music folder entirely.
